[package]
name = "nast"
version = "0.5.0"
edition = "2021"

[workspace]
members = [
    "crates/*",
]

[dependencies]
nast_dylib = { path = "crates/nast_dylib", version = "0.5.0" }
nast_json = { path = "crates/nast_json", version = "0.5.0" }
